# created by jeison guerrero 
AWSTemplateFormatVersion: "2010-09-09"
Description: 'Cloudformation for VPC'
Parameters: {}
Resources:
  MyVPC: 
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '172.16.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC 
# Public Subnet AZ 1
  PublicSubnet1A:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '172.16.1.0/24'
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags: 
        - Key: Name 
          Value: PublicSubnet1A
# Public App Private  AZ 1
  AppPrivateSubnet1A: 
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '172.16.2.0/24'
      AvailabilityZone: !Select [0, !GetAZs '']
# Public Data Privarcy Subnet AZ 1
  DataPrivateSubnet1A: 
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '172.16.3.0/24'
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags: 
        - Key: Name 
          Value: DataPrivateSubnet1A
# Public Subnet AZ 2
  PublicSubnet2B:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '172.16.4.0/24'
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags: 
        - Key: Name 
          Value: PublicSubnet2B
# Public App Private  AZ 1
  AppPrivateSubnet2B: 
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '172.16.5.0/24'
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags: 
        - Key: Name 
          Value: AppPrivateSubnet2B 
# Public Data Privarcy Subnet AZ 1
  DataPrivateSubnet2B: 
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '172.16.6.0/24'
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags: 
        - Key: Name 
          Value: DataPrivateSubnet2B
# Internet Gateway 
  InterentGateway: 
   Type: 'AWS::EC2::InternetGateway'
   Properties:
     Tags: 
        - Key: Name
          Value:  MyVPC-IGW 
# Attach IGW  to the VPC 
  AttachGateway: 
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref MyVPC 
      InternetGatewayId: !Ref InterentGateway  
# Route Tables 
  PublicRouteTable: 
    Type: 'AWS::EC2::RouteTable'
    Properties: 
      VpcId: !Ref MyVPC
      Tags: 
        - Key: Name 
          Value: PublicRouteTable
#Routes 
  PublicRoutes: 
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InterentGateway 
# Subnet Assocations 
  PublicSubnet1ARouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1A
      RouteTableId: !Ref PublicRouteTable
# Public Subnet 
  PublicSubnet2BRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2B
      RouteTableId: !Ref PublicRouteTable
# Security Group for ALB
  MyALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for Application Load Balancer
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MyALBSecurityGroup
 # Web Server /ALB  Security Group 
  WebserverSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable HTTP Access'
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80 
          CidrIp: '0.0.0.0/0'
# Launch Configuration
  MyLaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: t2.micro
# AutoScaling Group 
  MyAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '2'
      VPCZoneIdentifier:
        - !Ref AppPrivateSubnet1A
        - !Ref AppPrivateSubnet2B

#CPU Alarm 
  HighCPUAlarm: 
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Alarm when CPU exceeds 70#'
      MetricName: 'CPUUtilization'
      Namespace: 'AWS/ECS'
      Statistic: 'Average'
      Period: '300'
      EvaluationPeriods: '1'
      Threshold: '70'
      ComparisonOperator: 'GreaterThanThreshold'
      Dimensions:
        - Name: 'AutoScalingGroupName'
          Value: !Ref MyAutoScalingGroup
      AlarmActions: 
        - !Ref ScaleOutPolicy
# Scale Out Policy 
  ScaleOutPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties: 
      AutoScalingGroupName: !Ref MyAutoScalingGroup
      PolicyType: 'SimpleScaling'
      ScalingAdjustment: '1'
      Cooldown: '300'
      AdjustmentType: 'ChangeInCapacity'